# Homework 1: NumPy, Pandas, and Data Exploration
## CS 2100/4700: Introduction to Machine Learning

**Due Date:** 01/29/2026
**Total Points:** 100

## Instructions

- Complete all exercises in this notebook
- Include your code AND output for each question
- Comment your code where appropriate
- Do NOT use loops where vectorized operations are possible


## Part 1: NumPy Basics (20 points)

### Question 1.1 (10 points)

Given the following array of weekly hours worked:

```python
hours = np.array([40, 52, 35, 45, 60, 38, 42, 55, 48, 37])
```

a) Calculate and print the mean, min, and max hours

b) Find all values greater than 45 (use boolean indexing)

c) Count how many people worked more than 45 hours

In [15]:
import numpy as np

hours = np.array([40, 52, 35, 45, 60, 38, 42, 55, 48, 37])

# a) Calculate and print the mean, min, and max hours
mean_hours = np.mean(hours)
min_hours = np.min(hours)
max_hours = np.max(hours)
print(f"mean hours: {mean_hours} \n min hours: {min_hours} \n max_hours: {max_hours}")
# b) Find all values greater than 45 (use boolean indexing)
test_num = 45
values = hours[hours > test_num]
print(values)
# c) Count how many people worked more than 45 hours
print(len(values))

mean hours: 45.2 
 min hours: 35 
 max_hours: 60
[52 60 55 48]
4


### Question 1.2 (10 points)

Given this 2D array of student grades (rows = students, columns = [midterm, final, project]):

```python
grades = np.array([
    [85, 90, 88],
    [72, 68, 75],
    [90, 95, 92],
    [65, 70, 68]
])
```

a) Print the shape of the array

b) Extract all final exam scores (second column)

c) Calculate the average grade for each student (row means)

In [19]:
grades = np.array([
    [85, 90, 88],
    [72, 68, 75],
    [90, 95, 92],
    [65, 70, 68]
])

# a) Print the shape of the array
print(grades.shape)

# b) Extract all final exam scores (second column)
print(grades[:,1])

# c) Calculate the average grade for each student (row means)
row_mean = np.mean(grades , axis=1)
print(row_mean)

(4, 3)
[90 68 95 70]
[87.66666667 71.66666667 92.33333333 67.66666667]


## Part 2: Pandas Basics (30 points)

### Question 2.1 (10 points)

Create a DataFrame called `employees` with the following data:

| Name | Age | Department | Salary |
|------|-----|------------|--------|
| Alice | 28 | Engineering | 75000 |
| Bob | 35 | Marketing | 65000 |
| Carol | 42 | Engineering | 95000 |
| David | 31 | Sales | 55000 |
| Eve | 29 | Engineering | 80000 |

Then print: (a) the shape, (b) column names, and (c) data types

In [5]:
import pandas as pd

# Create the employees DataFrame


# a) Print the shape


# b) Print column names


# c) Print data types


### Question 2.2 (10 points)

Using the `employees` DataFrame:

a) Select only the 'Name' and 'Salary' columns

b) Filter for employees in the Engineering department

c) Filter for employees with Salary >= 70000 AND Age < 40

In [6]:
# a) Select only the 'Name' and 'Salary' columns


# b) Filter for employees in the Engineering department


# c) Filter for employees with Salary >= 70000 AND Age < 40


### Question 2.3 (10 points)

Using the `employees` DataFrame:

a) Calculate the mean salary

b) Use `value_counts()` to count employees in each Department

c) Add a new column `Senior` that is `True` if Age >= 35, otherwise `False`

In [7]:
# a) Calculate the mean salary


# b) Use value_counts() to count employees in each Department


# c) Add a new column 'Senior' that is True if Age >= 35, otherwise False



## Part 3: Exploring the Adult Dataset (50 points)

Run the cell below to load the UCI Adult Census Income dataset:

In [8]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

columns = ['age', 'workclass', 'fnlwgt', 'education', 'education_num',
           'marital_status', 'occupation', 'relationship', 'race',
           'sex', 'capital_gain', 'capital_loss', 'hours_per_week',
           'native_country', 'income']

df = pd.read_csv(url, names=columns, na_values=' ?', skipinitialspace=True)
print(f"Dataset loaded: {len(df)} records")

Dataset loaded: 32561 records


### Question 3.1 (10 points)

a) How many rows and columns are in the dataset?

b) Which columns have missing values and how many?

c) What percentage of people earn >50K?

In [9]:
# a) How many rows and columns are in the dataset?


# b) Which columns have missing values and how many?


# c) What percentage of people earn >50K?


### Question 3.2 (10 points)

a) What is the average age in the dataset?

b) What is the average hours_per_week?

c) What are the top 3 most common education levels?

In [10]:
# a) What is the average age in the dataset?


# b) What is the average hours_per_week?


# c) What are the top 3 most common education levels?


### Question 3.3 (10 points)

a) Filter the dataset for people aged 30 or younger. How many are there?

b) Filter for people with income '>50K' AND hours_per_week > 40. How many?

c) What percentage of people work in the 'Private' sector?

In [11]:
# a) Filter the dataset for people aged 30 or younger. How many are there?


# b) Filter for people with income '>50K' AND hours_per_week > 40. How many?


# c) What percentage of people work in the 'Private' sector?


### Question 3.4 (10 points)

a) Create a cross-tabulation of `sex` vs `income` showing row percentages

b) **Written Answer:** Based on the cross-tabulation, describe the income difference between males and females in 1-2 sentences.

In [12]:
# a) Create a cross-tabulation of sex vs income showing row percentages


**b) Written Answer:**

*[Your answer here]*


### Question 3.5 (10 points)

a) Create a new column `is_high_earner` that is 1 if income is '>50K', otherwise 0

b) Create a new column `age_group` using `pd.cut()` with bins [0, 30, 50, 100] and labels ['Young', 'Middle', 'Senior']

c) Show the first 5 rows with columns: age, age_group, income, is_high_earner

In [13]:
# a) Create a new column 'is_high_earner' that is 1 if income is '>50K', otherwise 0


# b) Create a new column 'age_group' using pd.cut()


# c) Show the first 5 rows with columns: age, age_group, income, is_high_earner


## Submission Checklist

Before submitting, ensure:

- [ ] All code cells show output
- [ ] Written answer is complete
- [ ] Notebook runs top to bottom without errors
- [ ] File named: `HW1_LastName_FirstName.ipynb`


## Grading Rubric

| Part | Points |
|------|--------|
| Part 1: NumPy | 20 |
| Part 2: Pandas | 30 |
| Part 3: Adult Dataset | 50 |
| **Total** | **100** |