# Homework 1: NumPy, Pandas, and Data Exploration
## CS 2100/4700: Introduction to Machine Learning

**Due Date:** 01/29/2026
**Total Points:** 100

## Instructions

- Complete all exercises in this notebook
- Include your code AND output for each question
- Comment your code where appropriate
- Do NOT use loops where vectorized operations are possible


## Part 1: NumPy Basics (20 points)

### Question 1.1 (10 points)

Given the following array of weekly hours worked:

```python
hours = np.array([40, 52, 35, 45, 60, 38, 42, 55, 48, 37])
```

a) Calculate and print the mean, min, and max hours

b) Find all values greater than 45 (use boolean indexing)

c) Count how many people worked more than 45 hours

In [15]:
import numpy as np

hours = np.array([40, 52, 35, 45, 60, 38, 42, 55, 48, 37])

# a) Calculate and print the mean, min, and max hours
mean_hours = np.mean(hours)
min_hours = np.min(hours)
max_hours = np.max(hours)
print(f"mean hours: {mean_hours} \n min hours: {min_hours} \n max_hours: {max_hours}")
# b) Find all values greater than 45 (use boolean indexing)
test_num = 45
values = hours[hours > test_num]
print(values)
# c) Count how many people worked more than 45 hours
print(len(values))

mean hours: 45.2 
 min hours: 35 
 max_hours: 60
[52 60 55 48]
4


### Question 1.2 (10 points)

Given this 2D array of student grades (rows = students, columns = [midterm, final, project]):

```python
grades = np.array([
    [85, 90, 88],
    [72, 68, 75],
    [90, 95, 92],
    [65, 70, 68]
])
```

a) Print the shape of the array

b) Extract all final exam scores (second column)

c) Calculate the average grade for each student (row means)

In [2]:
import numpy as np
grades = np.array([
    [85, 90, 88],
    [72, 68, 75],
    [90, 95, 92],
    [65, 70, 68]
])

# a) Print the shape of the array
print(grades.shape)

# b) Extract all final exam scores (second column)
print(grades[:,1])

# c) Calculate the average grade for each student (row means)
row_mean = np.mean(grades , axis=1)
print(row_mean)

(4, 3)
[90 68 95 70]
[87.66666667 71.66666667 92.33333333 67.66666667]


## Part 2: Pandas Basics (30 points)

### Question 2.1 (10 points)

Create a DataFrame called `employees` with the following data:

| Name | Age | Department | Salary |
|------|-----|------------|--------|
| Alice | 28 | Engineering | 75000 |
| Bob | 35 | Marketing | 65000 |
| Carol | 42 | Engineering | 95000 |
| David | 31 | Sales | 55000 |
| Eve | 29 | Engineering | 80000 |

Then print: (a) the shape, (b) column names, and (c) data types

In [ ]:
import pandas as pd

# Create the employees DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Carol', 'David', 'Eve'],
    'Age': [28, 35, 42, 31, 29],
    'Department': ['Engineering', 'Marketing', 'Engineering', 'Sales', 'Engineering'],
    'Salary': [75000, 65000, 95000, 55000, 80000]
}
employees = pd.DataFrame(data)
print(employees)
# a) Print the shape
print(f"Shape of employees: {employees.shape}")

# b) Print column names
print(f"this is the name of columns: {employees.columns}")

# c) Print data types
print(f"this is the data types: {employees.dtypes}")

    Name  Age   Department  Salary
0  Alice   28  Engineering   75000
1    Bob   35    Marketing   65000
2  Carol   42  Engineering   95000
3  David   31        Sales   55000
4    Eve   29  Engineering   80000
Shape of employees: (5, 4)
this is the name of columns: Index(['Name', 'Age', 'Department', 'Salary'], dtype='object')
this is the data types: Name          object
Age            int64
Department    object
Salary         int64
dtype: object


### Question 2.2 (10 points)

Using the `employees` DataFrame:

a) Select only the 'Name' and 'Salary' columns

b) Filter for employees in the Engineering department

c) Filter for employees with Salary >= 70000 AND Age < 40

In [59]:
import pandas as pd

# Create the employees DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Carol', 'David', 'Eve'],
    'Age': [28, 35, 42, 31, 29],
    'Department': ['Engineering', 'Marketing', 'Engineering', 'Sales', 'Engineering'],
    'Salary': [75000, 65000, 95000, 55000, 80000]
}
employees = pd.DataFrame(data)
# a) Select only the 'Name' and 'Salary' columns
print(employees[['Name', 'Salary']])

# b) Filter for employees in the Engineering department
engineer_employee = employees[employees['Department'] == 'Engineering']
print(engineer_employee)
# c) Filter for employees with Salary >= 70000 AND Age < 40
employee_sal_age = employees[(employees['Salary'] >= 70000) & (employees['Age'] < 40)]
print(employee_sal_age)

    Name  Salary
0  Alice   75000
1    Bob   65000
2  Carol   95000
3  David   55000
4    Eve   80000
    Name  Age   Department  Salary
0  Alice   28  Engineering   75000
2  Carol   42  Engineering   95000
4    Eve   29  Engineering   80000
    Name  Age   Department  Salary
0  Alice   28  Engineering   75000
4    Eve   29  Engineering   80000


### Question 2.3 (10 points)

Using the `employees` DataFrame:

a) Calculate the mean salary

b) Use `value_counts()` to count employees in each Department

c) Add a new column `Senior` that is `True` if Age >= 35, otherwise `False`

In [ ]:
import pandas as pd

# Create the employees DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Carol', 'David', 'Eve'],
    'Age': [28, 35, 42, 31, 29],
    'Department': ['Engineering', 'Marketing', 'Engineering', 'Sales', 'Engineering'],
    'Salary': [75000, 65000, 95000, 55000, 80000]
}
employees = pd.DataFrame(data)
# a) Calculate the mean salary
mean_salary = (employees['Salary']).mean()
print(mean_salary)
# b) Use value_counts() to count employees in each Department
employees_department = (employees['Department']).value_counts()
print(employees_department)
# c) Add a new column 'Senior' that is True if Age >= 35, otherwise False
employees['Senior'] = (employees['Age'] >= 35)
print(employees['Senior'])

74000.0
Department
Engineering    3
Marketing      1
Sales          1
Name: count, dtype: int64
0    False
1     True
2     True
3    False
4    False
Name: Senior, dtype: bool



## Part 3: Exploring the Adult Dataset (50 points)

Run the cell below to load the UCI Adult Census Income dataset:

In [8]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

columns = ['age', 'workclass', 'fnlwgt', 'education', 'education_num',
           'marital_status', 'occupation', 'relationship', 'race',
           'sex', 'capital_gain', 'capital_loss', 'hours_per_week',
           'native_country', 'income']

df = pd.read_csv(url, names=columns, na_values=' ?', skipinitialspace=True)
print(f"Dataset loaded: {len(df)} records")

Dataset loaded: 32561 records


### Question 3.1 (10 points)

a) How many rows and columns are in the dataset?

b) Which columns have missing values and how many?

c) What percentage of people earn >50K?

In [ ]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

columns = ['age', 'workclass', 'fnlwgt', 'education', 'education_num',
           'marital_status', 'occupation', 'relationship', 'race',
           'sex', 'capital_gain', 'capital_loss', 'hours_per_week',
           'native_country', 'income']

df = pd.read_csv(url, names=columns, na_values=' ?', skipinitialspace=True)
print(f"Dataset loaded: {len(df)} records")

# a) How many rows and columns are in the dataset?
num_rows, num_cols = df.shape
print(f"number of rows: {num_rows} \n number of columns: {num_cols}")

# b) Which columns have missing values and how many?
cols_missing_val = df.isna().sum()
print(cols_missing_val)
missing_only = cols_missing_val[cols_missing_val >0]
print(missing_only)

# c) What percentage of people earn >50K?
percentage = (df['income'] == '>50K').mean() *100
print(f"{percentage:.2f}%")


Dataset loaded: 32561 records
number of rows: 32561 
 number of columns: 15
age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64
Series([], dtype: int64)
24.08


### Question 3.2 (10 points)

a) What is the average age in the dataset?

b) What is the average hours_per_week?

c) What are the top 3 most common education levels?

In [18]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

columns = ['age', 'workclass', 'fnlwgt', 'education', 'education_num',
           'marital_status', 'occupation', 'relationship', 'race',
           'sex', 'capital_gain', 'capital_loss', 'hours_per_week',
           'native_country', 'income']

df = pd.read_csv(url, names=columns, na_values=' ?', skipinitialspace=True)
# a) What is the average age in the dataset?
avg_age = (df['age']).mean()
print(f"{avg_age:.2f}")

# b) What is the average hours_per_week?
avg_hours = (df['hours_per_week']).mean()
print(f"{avg_hours:.2f}")

# c) What are the top 3 most common education levels?
top3Education = df['education'].value_counts().head(3)
print(top3Education)

38.58
40.44
education
HS-grad         10501
Some-college     7291
Bachelors        5355
Name: count, dtype: int64


### Question 3.3 (10 points)

a) Filter the dataset for people aged 30 or younger. How many are there?

b) Filter for people with income '>50K' AND hours_per_week > 40. How many?

c) What percentage of people work in the 'Private' sector?

In [35]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

columns = ['age', 'workclass', 'fnlwgt', 'education', 'education_num',
           'marital_status', 'occupation', 'relationship', 'race',
           'sex', 'capital_gain', 'capital_loss', 'hours_per_week',
           'native_country', 'income']

df = pd.read_csv(url, names=columns, na_values=' ?', skipinitialspace=True)

# a) Filter the dataset for people aged 30 or younger. How many are there?
above_30 = (df['age'] >= 30).value_counts()
print(above_30[True])
# b) Filter for people with income '>50K' AND hours_per_week > 40. How many?
value = ((df['income'] == '>50K') & (df['hours_per_week'] > 40)).value_counts()
print(value[True])
# c) What percentage of people work in the 'Private' sector?
ppl_private = (df['workclass'] == 'Private').value_counts().mean()
print(ppl_private)

22850
3856
16280.5


### Question 3.4 (10 points)

a) Create a cross-tabulation of `sex` vs `income` showing row percentages

b) **Written Answer:** Based on the cross-tabulation, describe the income difference between males and females in 1-2 sentences.

In [37]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

columns = ['age', 'workclass', 'fnlwgt', 'education', 'education_num',
           'marital_status', 'occupation', 'relationship', 'race',
           'sex', 'capital_gain', 'capital_loss', 'hours_per_week',
           'native_country', 'income']

df = pd.read_csv(url, names=columns, na_values=' ?', skipinitialspace=True)
# a) Create a cross-tabulation of sex vs income showing row percentages
sex_vs_income = pd.crosstab(df['sex'], df['income'])
print(sex_vs_income)

income  <=50K  >50K
sex                
Female   9592  1179
Male    15128  6662


**b) Written Answer:**

*Based on the given information from the crosstab there are less females making >50k and there are more men making >50k a year. But in this comparision there is more men than women and there is more men making <=50k.*


### Question 3.5 (10 points)

a) Create a new column `is_high_earner` that is 1 if income is '>50K', otherwise 0

b) Create a new column `age_group` using `pd.cut()` with bins [0, 30, 50, 100] and labels ['Young', 'Middle', 'Senior']

c) Show the first 5 rows with columns: age, age_group, income, is_high_earner

In [47]:
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

columns = ['age', 'workclass', 'fnlwgt', 'education', 'education_num',
           'marital_status', 'occupation', 'relationship', 'race',
           'sex', 'capital_gain', 'capital_loss', 'hours_per_week',
           'native_country', 'income']

df = pd.read_csv(url, names=columns, na_values=' ?', skipinitialspace=True)

# a) Create a new column 'is_high_earner' that is 1 if income is '>50K', otherwise 0
df['is_high_earner'] = (df['income'] == '>50K').astype(int)
print(df['is_high_earner'])
# b) Create a new column 'age_group' using pd.cut()
bins = [0, 30, 50, 100]
group_names = ['Young', 'Middle', 'Senior']
df['age_group'] = pd.cut(df['age'], bins=bins, labels=group_names)
print(df['age_group'])
# c) Show the first 5 rows with columns: age, age_group, income, is_high_earner
df[['age', 'age_group', 'income', 'is_high_earner']].head()


0        0
1        0
2        0
3        0
4        0
        ..
32556    0
32557    1
32558    0
32559    0
32560    1
Name: is_high_earner, Length: 32561, dtype: int64
0        Middle
1        Middle
2        Middle
3        Senior
4         Young
          ...  
32556     Young
32557    Middle
32558    Senior
32559     Young
32560    Senior
Name: age_group, Length: 32561, dtype: category
Categories (3, object): ['Young' < 'Middle' < 'Senior']


age age_group income  is_high_earner
0   39    Middle  <=50K               0
1   50    Middle  <=50K               0
2   38    Middle  <=50K               0
3   53    Senior  <=50K               0
4   28     Young  <=50K               0

## Submission Checklist

Before submitting, ensure:

- [ ] All code cells show output
- [ ] Written answer is complete
- [ ] Notebook runs top to bottom without errors
- [ ] File named: `HW1_LastName_FirstName.ipynb`


## Grading Rubric

| Part | Points |
|------|--------|
| Part 1: NumPy | 20 |
| Part 2: Pandas | 30 |
| Part 3: Adult Dataset | 50 |
| **Total** | **100** |